# ===============================
# Spring 設定
# ===============================
spring:
  datasource:
    url: jdbc:mysql://${DB_URL:db}:${DB_PORT:3306}/${DB_NAME:acha_db}
    username: ${DB_USER:nacha_db_user}
    password: ${DB_PASSWORD:nacha}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

# ===============================
# ログ 設定
# ===============================
logging:
  config: classpath:logback.xml

# ===============================
# MyBatis 設定
# =============================== 
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

# ===============================
# Webjars 設定
# =============================== 
webjars:
  bootstrap: 5.1.3
  fontawesome: 6.1.0

# ===============================
# Server 設定
# =============================== 
server:
  error:
    include-exception: true
    include-stacktrace: always